# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      # - image: circleci/elixir:1.4
      - image: ciroque/phoenix-apps-build
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
      
#
# Dockerize
#
      - type: setup-docker-engine
        version: 17.06.0-ce

      - run:
          name: Docker Build
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            if [ "${CIRCLE_BRANCH}" == "alpha" ]; then
              docker build --build-arg mix_env=alpha -t ciroque/batch_process_coordination:$CIRCLE_BRANCH .
            elif [ "${CIRCLE_BRANCH}" == "beta" ]; then
              docker build --build-arg mix_env=beta -t ciroque/batch_process_coordination:$CIRCLE_BRANCH .
            else
              docker build --build-arg mix_env=prod -t ciroque/batch_process_coordination:$CIRCLE_BRANCH .
            fi

      - run:
          name: Publish container tagged with branch
          command: |
            docker push ciroque/batch_process_coordination:$CIRCLE_BRANCH
            docker tag ciroque/batch_process_coordination:$CIRCLE_BRANCH ciroque/batch_process_coordination:release

      - run:
          name: Publish latest if master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag ciroque/batch_process_coordination:release ciroque/batch_process_coordination:latest
              docker push ciroque/batch_process_coordination:latest
            fi

      - deploy:
          name: Deploy Alpha image to Docker Hub if alpha branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "alpha" ]; then
              docker tag ciroque/batch_process_coordination:release ciroque/batch_process_coordination:alpha
              docker push ciroque/batch_process_coordination:alpha
            fi

      - deploy:
          name: Deploy Beta image to Docker Hub if beta branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "beta" ]; then
              docker tag ciroque/batch_process_coordination:release ciroque/batch_process_coordination:beta
              docker push ciroque/batch_process_coordination:beta
            fi
