Mox.defmock(BatchProcessCoordination.ProcessMaintenanceMock, for: BatchProcessCoordination.ProcessMaintenanceBehaviour)
Mox.defmock(BatchProcessCoordination.BatchKeyMaintenanceMock, for: BatchProcessCoordination.BatchKeyMaintenanceBehaviour)
